import { PageHeader } from "./PageHeader";
import PageFooter from "./PageFooter";
import type { Metadata } from "next";
import "./globals.css";

// メタデータを定義
export const metadata: Metadata = {
  title: "Next.js13 Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <PageHeader />
        {children}
        <PageFooter />
      </body>
    </html>
  );
}
